### ISSUE TITLE
Create function return HTML not string to view

### ISSUE THREAD

**Issue by Tarek-Adra** [TahaniKarroum/smb215-restoproject#2]
i want to create a funciton return html code to view, and i can create this function under model or controller

but the problem is when i output it will convert HTML to Text so it will show HTML code not running it 
for Example : i have this class with function inside :

public class RatingProduct extends Model {
	
	public String getStars() {

		String res = "<div id=\"star-rating\">";
		res += "  <input type=\"radio\" name=\"example\" class=\"rating rating1\" value=\"1\" />";
		res += "    <input type=\"radio\" name=\"example\" class=\"rating rating2\" value=\"2\" />";
		res += "    <input type=\"radio\" name=\"example\" class=\"rating rating3\" value=\"3\" />";
		res += "   <input type=\"radio\" name=\"example\" class=\"rating rating4\" value=\"4\"   />";
		res += "    <input type=\"radio\" name=\"example\" class=\"rating rating5\" value=\"5\" />";
		res += "</div>";

		return res;
	}
......
}

when i call this function in view like : ${ratingProduct.getStars()}

it will show up the code HTML as text not as HTML 

checkout the screen shot 
![image](https://cloud.githubusercontent.com/assets/9800114/20772141/0b4eb772-b755-11e6-978a-fa87f79ec424.png)

**Comment by TahaniKarroum** [comment]
You should write in view : %{out.print(ratingProduct.getStars())}%

**Comment by Tarek-Adra** [comment]
Thanks :)

**Comment by TahaniKarroum** [comment]
Ur welcome
